// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALVSnPYGuFOKfq-9vvOAZAE1FjwBLO3go',
    appId: '1:74671224946:web:41c119ac64c26e44fa6aeb',
    messagingSenderId: '74671224946',
    projectId: 'accident-management-3eadf',
    authDomain: 'accident-management-3eadf.firebaseapp.com',
    storageBucket: 'accident-management-3eadf.firebasestorage.app',
    measurementId: 'G-2C0HPTT3JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJydCCRiglaH4AnWFtrKf7yjPdIz27HXA',
    appId: '1:74671224946:android:7c753ab9e14d6bc6fa6aeb',
    messagingSenderId: '74671224946',
    projectId: 'accident-management-3eadf',
    storageBucket: 'accident-management-3eadf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC94ObOg8ljlnqbdukPwGszTVVLDiKIYQ',
    appId: '1:74671224946:ios:b0323b27c8e7744cfa6aeb',
    messagingSenderId: '74671224946',
    projectId: 'accident-management-3eadf',
    storageBucket: 'accident-management-3eadf.firebasestorage.app',
    iosBundleId: 'com.example.accidentManagement4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC94ObOg8ljlnqbdukPwGszTVVLDiKIYQ',
    appId: '1:74671224946:ios:b0323b27c8e7744cfa6aeb',
    messagingSenderId: '74671224946',
    projectId: 'accident-management-3eadf',
    storageBucket: 'accident-management-3eadf.firebasestorage.app',
    iosBundleId: 'com.example.accidentManagement4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALVSnPYGuFOKfq-9vvOAZAE1FjwBLO3go',
    appId: '1:74671224946:web:0a77f6bc77f8e644fa6aeb',
    messagingSenderId: '74671224946',
    projectId: 'accident-management-3eadf',
    authDomain: 'accident-management-3eadf.firebaseapp.com',
    storageBucket: 'accident-management-3eadf.firebasestorage.app',
    measurementId: 'G-HZYVE4XT2V',
  );
}
